# -*- coding: utf-8 -*-
"""BigDataProposalLomba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HI9I34xgqK2Gf7k8bDR1WTKmGFbROHoc
"""

import pandas as pd
import matplotlib.pyplot as plt

# Muat dataset
dataset = pd.read_csv('annual-co-emissions-by-region.csv')

# Hitung total emisi per negara dan tahun
total_emisi_per_negara_tahun = dataset.groupby(['Code', 'Year'])['Annual CO2 emissions (zero filled)'].sum()

# Buat dataframe baru
df_negara_berkontribusi = pd.DataFrame(columns=['Year', 'Country', 'Total Emissions'])

# Looping untuk setiap tahun
for tahun in dataset['Year'].unique():
    # Filter data untuk tahun tertentu
    data_tahun = total_emisi_per_negara_tahun.loc[:, tahun]

    # Urutkan data berdasarkan total emisi pada tahun tertentu
    data_urut = data_tahun.sort_values(ascending=False)

    # Tambahkan data ke dataframe
    df_tahun = pd.DataFrame({'Year': tahun, 'Country': data_urut.index, 'Total Emissions': data_urut.values})
    df_negara_berkontribusi = pd.concat([df_negara_berkontribusi, df_tahun], ignore_index=True)

# # Tampilkan dataset hasil identifikasi dan pengurutan
# print(df_negara_berkontribusi)
df_negara_berkontribusi
df_negara_berkontribusi.to_csv('df_negara_berkontribusi.csv', index=False)

# Plot time series
fig, ax = plt.subplots(figsize=(120, 60))

# Looping untuk setiap negara dalam dataset terurut
for negara in df_negara_berkontribusi['Country'].unique():
    # Filter data negara
    data_negara = df_negara_berkontribusi[df_negara_berkontribusi['Country'] == negara]

    # Plot time series
    ax.plot(data_negara['Year'], data_negara['Total Emissions'], label=negara)

# Konfigurasi plot
ax.set_xlabel('Year')
ax.set_ylabel('Total Emissions')
ax.set_title('Time Series of Emissions by Country')
ax.legend(loc='upper left')

# Simpan plot sebagai file JPEG
plt.savefig('time_series_plot.jpeg', dpi=300, bbox_inches='tight')

# Tampilkan plot
plt.show()

